tasks:
  - name: Blog Sass
    init: (cd themes/soup && npm ci)
    command: (cd themes/soup && npm run compile:watch)
  - name: Portfolio
    before: cd portfolio
    init: npm install && npm run build
    command: npm run start
    openMode: split-left
  - name: Blog
    init: |
      sudo wget -q -O /opt/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_0.121.2_linux-amd64.deb
      sudo dpkg -i /opt/hugo.deb
      sudo rm /opt/hugo.deb
    command: hugo server
    openMode: split-right

ports:
  - port: 1313
    name: Blog
  - port: 3000
    name: Portfolio
